// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfficeEquip.Data;

#nullable disable

namespace OfficeEquip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712215042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfficeEquip.Models.Equipment", b =>
                {
                    b.Property<int>("IdEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipment"));

                    b.Property<int?>("EquipmentStatusIdStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentTypeIdType")
                        .HasColumnType("integer");

                    b.Property<int>("IdStatus")
                        .HasColumnType("integer");

                    b.Property<int>("IdType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEquipment");

                    b.HasIndex("EquipmentStatusIdStatus");

                    b.HasIndex("EquipmentTypeIdType");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("OfficeEquip.Models.EquipmentStatus", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdStatus");

                    b.ToTable("EquipmentStatuses");
                });

            modelBuilder.Entity("OfficeEquip.Models.EquipmentType", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdType"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdType");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("OfficeEquip.Models.Equipment", b =>
                {
                    b.HasOne("OfficeEquip.Models.EquipmentStatus", "EquipmentStatus")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentStatusIdStatus");

                    b.HasOne("OfficeEquip.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeIdType");

                    b.Navigation("EquipmentStatus");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("OfficeEquip.Models.EquipmentStatus", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("OfficeEquip.Models.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
